### PR TITLE
Configure registry_external_url in gitlab.rb

### PR DESCRIPTION
**Pull request by rlaurika**
In order to make use of the GitLab internal Docker registry, it needs to
be enabled in gitlab.rb using the registry_external_url option. Set this
option so that the registry is located under the same domain as GitLab
itself but in port 4567.

This enables us to use the registry for CI/CD pipelines: it will be
possible to build an image, push it to the registry and use that image
for subsequent jobs instead of building the image separately for every
single job. The nice thing about using GitLab's registry specifically is
that it is per project, so each project only has access to their own
images to keep things hygienic.

### CODE REVIEW

**Comment by rlaurika** [comment]
As far as I can tell this patch configures the external documentation exactly as specified in the documentation, yet I don't see anything binding to port 4567 on the host. I'm a bit mystified by this one.

**Comment by Jyrsa** [comment]
To rule out a simple issue: is the port forwarded from the docker container running the omnibus edition to the same port on the virtual machine?

**Comment by rlaurika** [comment]
@Jyrsa, you are correct. This makes the registry work, but I think we could still have a look at the default storage config for the registry to see if that is OK as is or if it needs additional config.

**Review by Jyrsa — APPROVED** [review]
Seems good to me. A registry helps with a lot.

**Pull request merged**
