### PR TITLE
Review cleanup

### PR DESCRIPTION
**Pull request by Jyrsa**

### CODE REVIEW

**Comment by bast** [comment]
Cool that you guys review each other!

**Comment by Jyrsa** [comment]
we figured a four-eyes system would be best if we want to maintain quality in the repo.

Initial crunch is now done so changes won't be as frequent and drastic and therefore reviewing is possible.

**Review by Vathasav — APPROVED** [review]
I just have some minor suggestions. 

Could we use variables to mount volume paths and folders where we store certificates? for example (/srv/gitlab-runner/config/certs/) inside a variable. 

Are you using all registered variables. Is this "admin_security_group" used somewhere?

**Review by Vathasav — APPROVED** [review]
I agree with the proposed changes. Suggested minor improvements.

**Comment by Vathasav** [comment]
I agree with the proposed changes. Suggested minor improvements.

**Pull request merged**
